### PR TITLE
add authentication for update rank use case

### PR DESCRIPTION
**Pull request by bellatoris**

### CODE REVIEW

**Comment by bellatoris** [comment]
Current dependencies on/for this PR:
* main
  * **PR #151** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/151" target="_blank">Graphite</a> 
    * **PR #152** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/152" target="_blank">Graphite</a> 
      * **PR #154** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/154" target="_blank">Graphite</a> 
        * **PR #155** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/155" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/155?utm_source=stack-comment).

**Review by Zeniuus — APPROVED** [review]

**Comment by bellatoris** [comment]
@bellatoris queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/155).

**Comment by bellatoris** [comment]
[Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/155) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

**Comment by bellatoris** [comment]
@bellatoris queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/155).

**Pull request merged**
