### PR TITLE
add external secret helm chart

### PR DESCRIPTION
**Pull request by bellatoris**

### CODE REVIEW

**Comment by bellatoris** [comment]
Current dependencies on/for this PR:
* main
  * **PR #102** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/102" target="_blank">Graphite</a> 
    * **PR #103** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/103" target="_blank">Graphite</a> 
      * **PR #104** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/104" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/104?utm_source=stack-comment).

**Review by Zeniuus — COMMENTED** [review]
차트를 추가하는 게 아니라 values.yaml만 추가하는 거죠?

어떤 차트 / 버전을 사용했는지를 README.md 같은 데 적어두면 좋을 듯 합니다.

**Comment by bellatoris** [comment]
> 차트를 추가하는 게 아니라 values.yaml만 추가하는 거죠?
> 
> 어떤 차트 / 버전을 사용했는지를 README.md 같은 데 적어두면 좋을 듯 합니다.

아하 네 좋네요. 근데 스완이 생각하신 secret create job 을 만들면 필요 없어질듯

**Comment by Zeniuus** [comment]
> 아하 네 좋네요. 근데 스완이 생각하신 secret create job 을 만들면 필요 없어질듯

ㅋㅋㅋ 그렇긴 한데, 혹시 안 할 수도 있으니 일단 추가해둔다?

**Comment by bellatoris** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/104?utm_source=stack-comment).


Job Reference: yaKyKHI4DL22rYVmgMTz

**Comment by bellatoris** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/104?utm_source=stack-comment).


Job Reference: VXwZMZbCIPcawtajM0VJ

**Pull request merged**
