### PR TITLE
rename conquestCount to conqueredCount

### PR DESCRIPTION
**Pull request by bellatoris**

### CODE REVIEW

**Comment by bellatoris** [comment]
Current dependencies on/for this PR:
* main
  * **PR #140** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/140" target="_blank">Graphite</a> 
    * **PR #141** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/141" target="_blank">Graphite</a> 
      * **PR #142** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/142" target="_blank">Graphite</a> 
        * **PR #143** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/143" target="_blank">Graphite</a> 
          * **PR #145** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/145" target="_blank">Graphite</a> 
            * **PR #146** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/146" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/146?utm_source=stack-comment).

**Review by SuhwanJee — APPROVED** [review]
엥 이건 안 하셔도 되는디

**Review by Zeniuus — APPROVED** [review]

**Comment by bellatoris** [comment]
[Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/146) rebased this pull request as part of a merge.

**Comment by bellatoris** [comment]
@bellatoris merged this pull request with [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/146).

**Pull request merged**
